import { useEffect, useState } from "react";
import { Activity, Check, ChevronDown, FileText, GitBranch, MessageSquare, Pencil, RefreshCw } from "lucide-react";
import type { Company, CompanyChat, CompanyTask } from "./company-model";
import { readRehearsals, REHEARSAL_STORAGE } from "./run-inspection";
import { RunInspector } from "./RunInspector";
import { runStatus, statusLabels } from "./task-rehearsal";
import { chatSteps, plannedSteps, relatedRehearsals } from "./work-detail";
import "./work-detail.css";

export function WorkDetail({ company, task, chat, edit, openTask, activity, canvas }: { canvas?: (() => void) | undefined; company: Company; task?: CompanyTask | undefined; chat?: CompanyChat | undefined; edit?: (() => void) | undefined; openTask?: ((task: CompanyTask) => void) | undefined; activity: () => void }) {
  const [tab, setTab] = useState<"steps" | "updates" | "output" | "rehearsals">("steps");
  const [history, setHistory] = useState(readRehearsals);
  const [selectedRun, setSelectedRun] = useState("");
  const linkedTask = chat?.taskId ? company.tasks?.find(t => t.id === chat.taskId) : undefined;
  const relatedTask = task || linkedTask;
  const runs = relatedRehearsals(history.runs, relatedTask?.id);
  const run = runs.find(r => r.id === selectedRun) || runs[0];
  const steps = task ? plannedSteps(company, task) : chat ? chatSteps(chat) : [];
  const tabs = [{ id: "steps", label: task ? "Steps" : "Timeline", Icon: GitBranch }, { id: "updates", label: "Progress updates", Icon: MessageSquare }, { id: "output", label: "Output", Icon: FileText }, { id: "rehearsals", label: `Rehearsals (${runs.length})`, Icon: Activity }] as const;
  useEffect(() => {
    const refresh = () => setHistory(readRehearsals());
    const onStorage = (event: StorageEvent) => { if (event.key === REHEARSAL_STORAGE || event.key === null) refresh(); };
    window.addEventListener("storage", onStorage); window.addEventListener("focus", refresh);
    return () => { window.removeEventListener("storage", onStorage); window.removeEventListener("focus", refresh); };
  }, []);
  return <section className={`co-work-detail ${chat ? "co-work-chat" : ""}`} aria-label={task ? "Task details" : "Chat details"}>
    <header className="co-work-header"><div><span className="co-section-kicker">{task ? "TASK WORKSPACE" : `CHAT DRAFT · ${chat?.engine || "No engine"}`}</span><p><span className="co-work-status">{task ? "Planned · Not started" : "Not sent"}</span><span>Engine not connected</span></p></div>{canvas && <button className="co-button co-button-primary" onClick={canvas}><GitBranch size={14} />Visual builder{task?.canvas ? ` (${task.canvas.nodes.length})` : ""}</button>}{edit && <button className="co-button" onClick={edit}><Pencil size={13} />Edit task</button>}</header>
    {task && <div className="co-work-context"><span>Created {new Date(task.createdAt).toLocaleString()}</span><span>{company.projects?.find(p => p.id === task.projectId)?.name || (task.projectId ? "Unavailable project" : "Company-wide")}</span><span>{task.schedule?.kind === "cron" ? `Schedule draft: ${task.schedule.expression} · ${task.schedule.timeZone}` : "Manual start"}</span></div>}
    <nav className="co-work-tabs" aria-label={task ? "Task detail panels" : "Chat detail panels"}>{tabs.map(({ id, label, Icon }) => <button type="button" key={id} aria-pressed={tab === id} onClick={() => setTab(id)}><Icon size={14} />{label}</button>)}</nav>
    {tab === "steps" && <div className="co-work-steps"><p className="co-work-caption">{task ? "Your configured plan—not a record of executed actions. Branches show their actual prerequisites and conditions." : "Recorded local prompts—not engine processing steps. No message below has been sent."}</p><ol>{steps.map((step, index) => <li key={step.id}><span className="co-step-marker">{chat ? <Check size={12} /> : index + 1}</span><details open={index === 0 || !!chat}><summary><span><strong>{step.title}</strong><small>{step.at ? new Date(step.at).toLocaleString() : `After: ${step.after}`}</small></span><em>{step.state}</em><ChevronDown size={13} /></summary><div><p>{step.description}</p><dl><dt>{task ? "Condition / team" : "Delivery"}</dt><dd>{step.condition}</dd>{task && <><dt>Approval</dt><dd>{step.approval}</dd></>}</dl></div></details></li>)}</ol>{task && !task.handoffs?.length && <p className="co-work-caption">No handoffs yet. Use Edit task → Workflow to add conditional steps.</p>}{task?.handoffs?.some(s => s.kind === "task") && <p className="co-work-caption">Linked tasks appear as handoff steps; their internal workflows are not expanded here.</p>}{linkedTask && <div className="co-work-linked"><span>Linked task · {linkedTask.title}</span><button className="co-button" onClick={() => openTask?.(linkedTask)}>Open task details</button></div>}{chat?.taskId && !linkedTask && <p className="co-form-error">The linked task is no longer available. The chat draft is unchanged.</p>}</div>}
    {tab === "updates" && <div className="co-work-empty"><MessageSquare size={24} /><h3>No engine progress updates yet.</h3><p>When an engine connection supports it, this view can show published status messages and concise explanations of actions. This workspace currently has no connected engine session.</p><small>Private internal reasoning is not displayed. Rehearsal logs are recorded simulation events, not model thinking.</small></div>}
    {tab === "output" && <div className="co-work-empty"><FileText size={24} /><h3>{task ? "No live output yet." : "No assistant reply yet."}</h3><p>{task ? "This task has not run through an engine. No generated answer, command output, changed files, or artifacts have been recorded." : "These prompts are local drafts. No model has processed them or generated a response."}</p>{runs.length > 0 && <button className="co-button" onClick={() => setTab("rehearsals")}>Inspect saved rehearsal output</button>}</div>}
    {tab === "rehearsals" && <div className="co-work-rehearsals"><div className="co-work-rehearsal-heading"><p>{chat ? "Rehearsals of the linked task, not chat execution." : "Saved simulations of this task, matched by task ID."} Each run keeps its original plan snapshot.</p><button className="co-button" onClick={() => setHistory(readRehearsals())}><RefreshCw size={13} />Refresh history</button></div>{history.error && <p className="co-form-error" role="alert">{history.error}</p>}{runs.length ? <><label className="co-work-run-picker">Rehearsal run<select value={run!.id} onChange={e => setSelectedRun(e.target.value)}>{runs.map(r => <option key={r.id} value={r.id}>{new Date(r.createdAt).toLocaleString()} · {statusLabels[runStatus(r)]} · {r.id.slice(0, 8)}</option>)}</select></label><RunInspector key={run!.id} run={run!} /></> : <div className="co-work-empty"><Activity size={24} /><h3>No saved rehearsals.</h3><p>{chat && !linkedTask ? "Make a prompt a task before testing its workflow." : "Test the plan in Activity & approvals. Rehearsals never run agents or grant permission for real actions."}</p></div>}<button className="co-button" onClick={activity}>Open Activity & approvals</button></div>}
  </section>;
}
